//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservice.evolucion.upc.edu.pe/", ConfigurationName="DemoJenkins_JavaServer.CalculadoraWS")]
    public interface CalculadoraWS {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://webservice.evolucion.upc.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.evolucion.upc.edu.pe/CalculadoraWS/RestaRequest", ReplyAction="http://webservice.evolucion.upc.edu.pe/CalculadoraWS/RestaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaResponse Resta(DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.evolucion.upc.edu.pe/CalculadoraWS/RestaRequest", ReplyAction="http://webservice.evolucion.upc.edu.pe/CalculadoraWS/RestaResponse")]
        System.Threading.Tasks.Task<DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaResponse> RestaAsync(DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://webservice.evolucion.upc.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.evolucion.upc.edu.pe/CalculadoraWS/SumaRequest", ReplyAction="http://webservice.evolucion.upc.edu.pe/CalculadoraWS/SumaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaResponse Suma(DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservice.evolucion.upc.edu.pe/CalculadoraWS/SumaRequest", ReplyAction="http://webservice.evolucion.upc.edu.pe/CalculadoraWS/SumaResponse")]
        System.Threading.Tasks.Task<DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaResponse> SumaAsync(DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Resta", WrapperNamespace="http://webservice.evolucion.upc.edu.pe/", IsWrapped=true)]
    public partial class RestaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int y;
        
        public RestaRequest() {
        }
        
        public RestaRequest(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RestaResponse", WrapperNamespace="http://webservice.evolucion.upc.edu.pe/", IsWrapped=true)]
    public partial class RestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public RestaResponse() {
        }
        
        public RestaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Suma", WrapperNamespace="http://webservice.evolucion.upc.edu.pe/", IsWrapped=true)]
    public partial class SumaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int y;
        
        public SumaRequest() {
        }
        
        public SumaRequest(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SumaResponse", WrapperNamespace="http://webservice.evolucion.upc.edu.pe/", IsWrapped=true)]
    public partial class SumaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public SumaResponse() {
        }
        
        public SumaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CalculadoraWSChannel : DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculadoraWSClient : System.ServiceModel.ClientBase<DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS>, DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS {
        
        public CalculadoraWSClient() {
        }
        
        public CalculadoraWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculadoraWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculadoraWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaResponse DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS.Resta(DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaRequest request) {
            return base.Channel.Resta(request);
        }
        
        public int Resta(int x, int y) {
            DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaRequest inValue = new DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaRequest();
            inValue.x = x;
            inValue.y = y;
            DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaResponse retVal = ((DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS)(this)).Resta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaResponse> DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS.RestaAsync(DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaRequest request) {
            return base.Channel.RestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaResponse> RestaAsync(int x, int y) {
            DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaRequest inValue = new DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.RestaRequest();
            inValue.x = x;
            inValue.y = y;
            return ((DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS)(this)).RestaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaResponse DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS.Suma(DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaRequest request) {
            return base.Channel.Suma(request);
        }
        
        public int Suma(int x, int y) {
            DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaRequest inValue = new DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaRequest();
            inValue.x = x;
            inValue.y = y;
            DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaResponse retVal = ((DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS)(this)).Suma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaResponse> DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS.SumaAsync(DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaRequest request) {
            return base.Channel.SumaAsync(request);
        }
        
        public System.Threading.Tasks.Task<DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaResponse> SumaAsync(int x, int y) {
            DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaRequest inValue = new DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.SumaRequest();
            inValue.x = x;
            inValue.y = y;
            return ((DemoJenkins_NetClient.BussLog.DemoJenkins_JavaServer.CalculadoraWS)(this)).SumaAsync(inValue);
        }
    }
}
